### ISSUE TITLE
Doesn't work at all?

### ISSUE THREAD

**Issue by Natanji** [quassy/pwdhash#4]
Hey there,
I've tried the different ways of using this and it plain doesn't work at all.
If I open the web page https://quassy.github.io/pwdhash/, the Pwdhash field will be stuck at "type to generate" no matter what I type in the two fields above. I'm also confused because the way I understand it, this is supposed to be a Cambridge implementation which allows user salt+iterations to be configurable - none of which can be seen on that site.

If I click on the link https://addons.mozilla.org/de/developers/addon/pwdhash-sidebar then it tells me I'm forbidden to see the site.

**Comment by quassy** [comment]
1. Web page: This was an issue with how I added browser functionality and didn't test it properly. Should be fixed now.
2. Cambridge: The readme was confusing, it's supposed to support the Cambridge algorithm in the future but at the moment only supports Stanford. Cleared up now.
3. AMO link: That was the internal link, you can find the [extension here on AMO](https://addons.mozilla.org/de/firefox/addon/pwdhash-sidebar/). Fixed.

Thanks for testing and your report!

**Comment by quassy** [comment]
The issues should be fixed and the new version will land on AMO soon. Please reopen if not.
