### ISSUE TITLE
Wrong address with multiple firefox windows

### ISSUE THREAD

**Issue by orzechow** [quassy/pwdhash#8]
When having multiple Firefox windows open, the Plug-In wrongly prefills the address field with the address of the first opened window.

So as an example, I have two windows (not tabs):
- first: _wikipedia.org_
- second: _myloginsite.net_

I have the second window up and focused, but calling the Plug-In with F8, results in _wikipedia.org_ filled into the address field.

**Comment by quassy** [comment]
Fix commited and uploaded.
